<!-- RRP78 Roshan Patel -->

<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ page import="java.io.*,java.util.*,java.sql.*"%>
<%@ page import="javax.servlet.http.*,javax.servlet.*"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>CustomerRep Home</title>
</head>
<body>


	<h1 align="center">Ticket Reservation System</h1>
	<h2 align="center">Manager Home Page</h2>

	<div align="right">
		<b> Logged in as <%=session.getAttribute("username")%> (<%=session.getAttribute("userType")%>).
		</b> <br> <a href='../LogOut.jsp'>Log out</a>
	</div>

	<h3>Revenue Information</h3>
	<div align='right'>
		<a href="../HomePages/CustomerRepHome.jsp">Back to Customer Rep Home</a>
	</div>
	<br>

	<h4>Revenue by flight</h4>

	<%
		try {
			String Flight = request.getParameter("flight");
			out.println("Flight: " + Flight);

			String url = "jdbc:mysql://mydbinstance.cvlvoepmucx7.us-east-2.rds.amazonaws.com:3306/trs";
			Connection connection = null;
			Class.forName("com.mysql.jdbc.Driver");
			connection = DriverManager.getConnection(url, "rshn", "youknownothingJonSnow");

			Statement statement = connection.createStatement();
			String command = "SELECT COUNT(DISTINCT resNo) count FROM Purchases WHERE CONCAT(airlineID, flightNumber) = '"
					+ Flight + "'";
			ResultSet result = statement.executeQuery(command);
			if (result.next()) {
				int count = result.getInt("count");
				int sum = count * 50;
				out.println("<br><br>Number of reservations " + count);
				out.println("<br><br>Revenue generated by this flight $ " + sum);
			}
			result.close();
			statement.close();
			connection.close();
		} catch (Exception e) {

		}
	%>

	<br>
	<br>
	<br>
	<a href="../HomePages/CustomerRepHome.jsp">Back to Customer Rep Home</a>


</body>
</html>

